-- This module is the root of the GlobalLanglandsReciprocityCanonicalLaneLean Lean proof package.
import GlobalLanglandsReciprocityCanonicalLaneLean.Basic
import GlobalLanglandsReciprocityCanonicalLaneLean.SourcePackage
import GlobalLanglandsReciprocityCanonicalLaneLean.SourceDependencies
import GlobalLanglandsReciprocityCanonicalLaneLean.Formalization
import GlobalLanglandsReciprocityCanonicalLaneLean.ReviewerBridge
import GlobalLanglandsReciprocityCanonicalLaneLean.TheoremStatement
import GlobalLanglandsReciprocityCanonicalLaneLean.MathlibObjects
import GlobalLanglandsReciprocityCanonicalLaneLean.AdmissibleClass
import GlobalLanglandsReciprocityCanonicalLaneLean.Projection
import GlobalLanglandsReciprocityCanonicalLaneLean.BridgeLemmas
import GlobalLanglandsReciprocityCanonicalLaneLean.GateLemmas
import GlobalLanglandsReciprocityCanonicalLaneLean.FinalTheorem
import GlobalLanglandsReciprocityCanonicalLaneLean.MathlibStatement
